/**
 * Validates the repository's config.yaml and compiles it into
 * packages/server/src/config.generated.ts plus config.schema.json. Runs under
 * plain Node (type stripping), in CI, and as wrangler's build command, so an
 * invalid configuration cannot be deployed.
 *
 * Usage: node packages/server/scripts/compile-config.ts [path/to/config.yaml]
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { centralConfigJsonSchema, compileCentralConfig, ConfigError } from "@gate/core";

const serverRoot = resolve(import.meta.dirname, "..");
const repositoryRoot = resolve(serverRoot, "../..");
const source = resolve(process.cwd(), process.argv[2] ?? resolve(repositoryRoot, "config.yaml"));
const generated = resolve(serverRoot, "src/config.generated.ts");
const schemaFile = resolve(repositoryRoot, "config.schema.json");

function writeIfChanged(path: string, content: string): void {
  if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
    writeFileSync(path, content);
  }
}

try {
  const { config, warnings } = compileCentralConfig(readFileSync(source, "utf8"));
  for (const warning of warnings) {
    process.stderr.write(`warning: ${warning}\n`);
  }
  writeIfChanged(
    generated,
    [
      "// Generated by scripts/compile-config.ts from config.yaml. Do not edit.",
      'import type { CentralConfig } from "@gate/core";',
      "",
      `export const compiledConfig: CentralConfig = ${JSON.stringify(config, null, 2)};`,
      "",
    ].join("\n"),
  );
  writeIfChanged(schemaFile, `${JSON.stringify(centralConfigJsonSchema(), null, 2)}\n`);
  process.stdout.write(`config ok: ${source}\n`);
} catch (error) {
  if (error instanceof ConfigError) {
    process.stderr.write(`${source}: ${error.message}\n`);
    process.exit(1);
  }
  throw error;
}
